name: Update Maintainers Across Organization

on:
  push:
    paths:
      - "${{ vars.ACCESS_CONFIG_FILE }}"
      - "maintainer_config.yaml"
      - ".github/workflows/org_update_maintainers.yml"
  workflow_dispatch: {}

env:
  ACCESS_CONFIG_FILE: ${{ vars.ACCESS_CONFIG_FILE || 'access_config.yaml' }}

jobs:
  update-maintainers:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout governance repo
        uses: actions/checkout@v4

      - name: Show config filename
        run: |
          echo "Using access config file: $ACCESS_CONFIG_FILE"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pyyaml requests

      - name: Download Maintainers Generator
        run: |
          curl -L -o generate-maintainers.py \
            https://raw.githubusercontent.com/<ORG>/<REPO>/main/generate-maintainers.py
          chmod +x generate-maintainers.py

      - name: Load repository list from CLOWarden access config
        id: load_repos
        run: |
          echo "Loading repos from: $ACCESS_CONFIG_FILE"
          echo "repos=$(yq -o=json '.repositories[].name' "$ACCESS_CONFIG_FILE" | jq -c '.')" >> $GITHUB_OUTPUT

      - name: Iterate through repos
        run: |
          repos=$(echo '${{ steps.load_repos.outputs.repos }}' | jq -r '.[]')

          for repo in $repos; do
            echo "**** Processing $repo ****"

            # TEMP DIR
            mkdir work
            cd work

            echo "Cloning $repo…"
            git clone "https://github.com/${{ github.repository_owner }}/$repo.git" repo_dir
            cd repo_dir

            # Detect repo-level override
            if [[ -f "maintainer_config.yaml" ]]; then
              CONFIG_FILE="maintainer_config.yaml"
            else
              CONFIG_FILE="../../maintainer_config.yaml"
            fi

            echo "Using config file: $CONFIG_FILE"

            python ../../generate-maintainers.py \
              --repo "$repo" \
              --config "$CONFIG_FILE" \
              --output MAINTAINERS.md \
              --no-fetch

            # Skip PR if no change
            if git diff --quiet MAINTAINERS.md; then
              echo "No changes for $repo"
              cd ../..
              rm -rf work
              continue
            fi

            echo "Changes detected → preparing PR"

            git config user.name "github-actions"
            git config user.email "github-actions@github.com"

            BRANCH="update-maintainers-$(date +%s)"
            git checkout -b "$BRANCH"

            git add MAINTAINERS.md
            git commit -m "Automated update of MAINTAINERS.md"
            git push origin "$BRANCH"

            echo "Opening PR…"
            gh pr create \
              --repo "${{ github.repository_owner }}/$repo" \
              --title "Automated update of MAINTAINERS.md" \
              --body "This PR updates the MAINTAINERS.md file based on the latest governance data."

            cd ../..
            rm -rf work
          done

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}